<?php
use Admin\Lib\Tabadmin;
use Admin\Lib\Simba;
use Laminas\Session\Container as SessionContainer;

simba::$container=$this->container;
$tab=new Tabadmin($this,$this->config);
?>


<h1>Галерея внутри контента</h1>
<form action="" method="post">
<input type="hidden" value="create_new_gallery" name="form_action">
<input type="submit" value="Создать новую галерею" />
</form>
<br><br>



<form action="" method="post" enctype="multipart/form-data">
    <input type="hidden" value="edit_gallery" name="form_action">
<?php



$tab->col_name=array('Порядок','Фото','Подпись','Операция');
$tab->flag_out_form=false;
$tab->row_dop_type(4,'gallery_number','class=txt onChange="this.form.submit()"',$this->gallery_numbers,$this->gallery_numbers,0,0,0,0,array(0,0));
$tab->row_dop_value($this->gallery_number,0);
$tab->caption('Выберите номер галереи для редактирования:','',0);
	
$tab->row_start_type(false,2,'poz[0]','size=4');
$tab->row_start_type(false,32,'img[0]','',0,0,"",0,0,array("gallery","310_232"));
$tab->row_start_type(false,3,'alt[0]','cols=80 rows=4');
$tab->row_start_type(false,19,'save[0]','',0,0,0,0,0,array(1,'Добавить'));



$tab->row_def_type(false,2,$tab->create_array_names($this->items['id'],'poz'),'size=4');
$tab->row_def_type(false,32,$tab->create_array_names($this->items['id'],'img'),'',0,0,"",0,0,array("gallery","310_232"));
$tab->row_def_type(false,3,$tab->create_array_names($this->items['id'],'alt'),'cols=80 rows=4');
$tab->row_def_type(false,17,$tab->create_array_names($this->items['id'],'save','del'),'',0,0,0,0,0,array(1,0,'Сохранить,Удалить'));

$tab->row_all_value (false,$this->items['poz']);
$tab->row_all_value (false,$this->items['img']);
$tab->row_all_value (false,$this->items['alt']);
$tab->row_all_value (false,[]);

$tab->global_action=array(1,1);
$tab->global_action_id_array=implode(',',$this->items['id']);
$tab->button_all_operation_names[1]='saveall';//имя кнопки сохранить все


$tab->tab_print();

?>
</form>


