<?php
/*
* генерирует jqgrid
* на входе:
* $options - опции из сооттветсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса глобального
*/
use Zend\Json\Json;

Json::$useBuiltinEncoderDecoder = !function_exists("json_encode");

$options=$this->options;

//\Zend\Debug\Debug::dump($options["layout"]["colModel"]);
//удалим всю информацию о плагинах, она не нужна
foreach ($options["layout"]["colModel"] as $k=>$v){
    unset($options["layout"]["colModel"][$k]["plugins"]);
}


$options["layout"]["datatype"]="json";
$options["layout"]["mtype"]="GET";
$options["layout"]["url"]=$this->url("adm/io-jqgrid",
                           [
                               "interface"=>$interface,
                               "action" => "readjqgrid"
                           ]
                           );

$options["layout"]["editurl"]=$this->url("adm/io-jqgrid",
                           [
                               "interface"=>$interface,
                               "action" => "editjqgrid"
                           ]
                           );

$options["layout"]["pager"]="#".$options["container"]."_pager";

/*опции навигации*/
$navgrid_options=$options["layout"]["navgrid"];
unset($options["layout"]["navgrid"]);
if (!isset($navgrid_options["delOptions"])){
    $navgrid_options["delOptions"]=[];
}
if (!isset($navgrid_options["addOptions"])){
    $navgrid_options["addOptions"]=[];
}
if (!isset($navgrid_options["editOptions"])){
    $navgrid_options["editOptions"]=[];
}
if (!isset($navgrid_options["viewOptions"])){
    $navgrid_options["viewOptions"]=[];
}
if (!isset($navgrid_options["searchOptions"])){
    $navgrid_options["searchOptions"]=[];
}
if (!isset($navgrid_options["button"])){
    $navgrid_options["button"]=[];
}

/*все опции в грид*/
$jqgrid= json::encode($options["layout"], false, ['enableJsonExprFinder' => true]);


if (isset($options["caption"])){
    echo $options["caption"];
}
?>
<table id="<?=$options["container"]?>"></table> 
<div id="<?=$options["container"]?>_pager"></div>

<script type="text/javascript">
$(function () {
"use strict";
var jqgrid_options=<?=$jqgrid?>,
    navgrid_button_options=<?=json::encode($navgrid_options["button"],true)?>,
    navgrid_edit_options=<?=json::encode($navgrid_options["editOptions"],true)?>,
    navgrid_add_options=<?=json::encode($navgrid_options["addOptions"],true)?>,
    navgrid_del_options=<?=json::encode($navgrid_options["delOptions"],true)?>,
    navgrid_view_options=<?=json::encode($navgrid_options["viewOptions"],true)?>,
    navgrid_search_options=<?=json::encode($navgrid_options["searchOptions"],true)?>;
jqgrid_options.dataProxy=$.jgrid.ext.ajaxFormProxy;
jqgrid_options.useDataProxy=true;
jqgrid_options.pager='#<?=$options["container"]?>_pager';
/*jqgrid_options.ajaxRowOptions={
    contentType:'multipart/form-data'
}
*/

navgrid_edit_options.useDataProxy=true;
navgrid_edit_options.onInitializeForm =function(formid){$(formid).attr('method','POST');$(formid).attr('action','');$(formid).attr('enctype','multipart/form-data');};
navgrid_add_options.useDataProxy=true;
navgrid_add_options.onInitializeForm =function(formid){$(formid).attr('method','POST');$(formid).attr('action','');$(formid).attr('enctype','multipart/form-data');};
    
$("#<?=$options["container"]?>").jqGrid(jqgrid_options);
var jqgridnavGrid=$("#<?=$options["container"]?>").navGrid('#<?=$options["container"]?>_pager', navgrid_button_options, /*кнопки в панели*/
            navgrid_edit_options, //опции в окно при редактировании edit
            navgrid_add_options, // опции в окно при добавлении add
            navgrid_del_options,  // delete instead that del:false we need this
            navgrid_search_options, //окно поиска
            navgrid_view_options); //опции при просмотре записи в окошке
/*
//доп.кнопки в панели
jqgridnavGrid.navButtonAdd('#<?=$options["container"]?>_pager',
                {
                    caption:"",
                    buttonicon:"ui-icon-locked",
                    onClickButton:null,
                    position: "last",
                    title:"Доступ к интерфейсу",
                    id : "",
                    cursor: "pointer"
                });
*/
});

</script>
<?php
if (isset($options["podval"])){
    echo $options["podval"];
}

?>

<script>
    //большой выбор путем autocomplite
        $("#question_tags").tagit({
        removeConfirmation: true,
        allowSpaces: true,
        animate: false,
        tabIndex: 3,
        autocomplete: {
            minLength: 3,
            source: function(request, response) {
                $.ajax({
                    url: "/adm/io-jqgrid",
                    data: {
                        term: request.term
                    },
                    dataType: "json",
                    success: function(data) {
                        response($.map(data, function(item) {
                            return {
                                label: item.display_name,
                                value: item.display_name,
                                ident: item.name,
                                image_url: item.image_url
                            }
                        }))
                    }
                })
            },
            open: function() {
                $(".ui-autocomplete:visible").css({
                    top: "+=15",
                    left: "+=-5"
                })
            },
            create: function(event, ui) {
                $(this).data("ui-autocomplete")._renderItem = function(ul, item) {
                    ul.addClass("autocomplete_tags");
                    var tagImage = "";
                    if (item.image_url) {
                        tagImage = '<img class="icon_suggest icon_tag-img" src="' + item.image_url + '" alt="user avatar" />'
                    } else {
                        tagImage = '<svg class="icon_suggest icon_tag_small" viewBox="0 0 32 32"><use xlink:href="images/sprite_0.1.svg#icon_tag"></use></svg>'
                    }
                    return $("<li class='ui-search-type-tag'>").append("<a>" + tagImage + "<span>" + item.label + "</span>" + "</a>").appendTo(ul)
                }
            }
        }
    });

</script>
