<?php
$options=$this->options;
//\Zend\Debug\Debug::dump($options["main"]["type"]);
?>

<div id="<?=$options["main"]["container"]?>">
<?=$options["main"]["caption"]?>
<?php
foreach($options["main"]["type"] as $type=>$config_section){
    echo $this->partial($type,["options"=>$options[$config_section],"type"=>$config_section,"interface"=>$options["interface"]]);
}
?>
<p><?=$options["main"]["podval"]?></p>
</div>