<?php
/*
* генерирует zform
* на входе:
* $options - опции из соответсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса
* $form - сама форма в виде данных формата Zend
*/

$options=$this->options;

//\Zend\Debug\Debug::dump($options);
?>
<div id="<?=$options["container"]?>" class="zform-default" <?=$options["container-attr"]?>>
<?php
$form = $this->form;
$form->prepare();
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
foreach ($form as $k=>$item){
    $i=$form->get($k);
    if ($k=="submit"){
        $i->setAttribute("class","btn btn-primary btn-sm");
        ?>
    <?=$this->formButton($form->get($k));?>
    <?php
    } else {
        $a="form-control form-control-sm";
        if ($i->hasAttribute("class")){
            $a.=" ".$i->getAttribute("class");
        }
        $i->setAttribute("class",$a);
?>
  <div class="form-group">
    <?=$formLabel->openTag($i) . $i->getOption('label').$formLabel->closeTag();?>
      <?=$this->FormInput($i)?>
    <?=$this->formElementErrors($i)?>
  </div>
<?php
    }
}
     ?>

<?= $this->form()->closeTag() ?>
</div>

