<?php
/*
* генерирует zform
* на входе:
* $options - опции из соответсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса
* $form - сама форма в виде данных формата Zend
*/

$options=$this->options;

//\Zend\Debug\Debug::dump($options);
?>
<div id="<?=$options["container"]?>" class="zform-default">
<?php
$form = $this->form;
$form->prepare();

echo $this->form()->openTag($form);
?>
  <div class="form-group">
    <label for="exampleInputEmail1">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
    <?=$this->formElement($form->get('submit'));?>
<?= $this->form()->closeTag() ?>
<?php

    /*foreach ($form as $k=>$item){
    if (!in_array($k,['captcha','security',"submit"])){
    ?>
    <div class="form_element">
    <?= $this->formRow($form->get($k)) ?>
    </div>
    <?php
    }
}*/
?>


</div>

