<?php
if (!empty($folder)){
    $folder="/".$folder;
}
$f=realpath($dir."/../../public/{$type}/admin{$folder}")."/".$file;
//заголовки
$ext=pathinfo($f,PATHINFO_EXTENSION);
switch ($ext){
    case "css":header ("Content-Type: text/css");break;
    case "js":header ("Content-Type: application/javascript");break;
    case "gif":header ("Content-Type: image/gif");break;   
    case "jpeg":
    case "jpg":header ("Content-Type: image/jpeg");break;
    case "png":header ("Content-Type: image/png");break;
    case "jpeg":header ("Content-Type: font/woff2");break;
    case "eot":header ("Content-Type: application/vnd.ms-fontobject");break;
    case "woff":header ("Content-Type: font/woff");break;
    case "ttf":
    case "map":header ("Content-Type: application/octet-stream");break;
    case "svg":header ("Content-Type: image/svg+xml");break;
}


echo file_get_contents($f);