<frameset cols="200,*" framespacing="1" frameborder="1" border="1" bordercolor="#000000">
 <frame src="/admin/left/<?=$this->session_id;?>" name="leftFrame" scrolling="no" marginwidth="1">
    <frame src="/admin/maindefault/?sid=<?=$this->session_id;?>" name="mainFrame">
    </frameset>
        <noframes>
                <body bgcolor="#FFFFFF">
                            <p>No frame support</b>.</p>
                            </body>
                        </noframes>