<div class="form-signin">
    <?php
    $form = $this->form;
    $form->prepare();

    echo $this->form()->openTag( $form );
    ?>

    <table cellspacing="0" cellpadding="5">

        <tr>
            <td rowspan="4" ><img src="/img/simba.jpg" alt="Simba ZF3">
            </td>
            <td>Login: </td>
            <td>
                <?= $this->formElement($form->get('login')) ?>
            </td>
        </tr>
        <tr>
            <td>Password: </td>
            <td>
                <?= $this->formElement($form->get('password')) ?>
                <?php
            if ($this->error){
                echo '<p class="error">Ошибка авторизации</p>';
            }
    ?>
            </td>
        </tr>
        <tr>
            <td colspan="2" align="right">
                <?= $this->formElement($form->get('submit')) ?>
            </td>
        </tr>

    </table>
    <?= $this->form()->closeTag() ?>
</div>