<?php
use Admin\Lib\Ioline;

$this->dialog_message="";
$this->dialog_title="";

$io_line_interface=new Ioline($this->container,$this);
$io_line_interface->create_interface($this->table);

$io_line_interface->print_interface();

if(isset($io_line_interface->design_tables_text_interfase['coment0']) && empty($this->dialog_message)){
    echo $io_line_interface->design_tables_text_interfase['coment0'];
}

?>
<div id="constr_dialog" title="<?=$this->dialog_title;?>" style="color: red"><h2><?=$this->dialog_message?></h2></div>
<script language="javascript" type="text/javascript">
$( "#constr_dialog" ).dialog({
    resizable: true,
    width: "auto",
    modal: true,
    autoOpen:'<?=$this->dialog_message?>'>'',
    buttons: [
        {
            text: "Ok",
            click: function() {
                $( this ).dialog( "close" );
            }
        }
    ]
});
</script>