<?php
/*
* генерирует zform
* на входе:
* $options - опции из соответсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса
* $form - сама форма в виде данных формата Zend
*/

$options=$this->options;

if (!empty($options["options"]["actionsEvent"])){
    $actionEvent=$options["options"]["actionsEvent"];
} else {
    $actionEvent=[];
}
//\Zend\Debug\Debug::dump($options);


$get="";
if (isset($_GET)){
    $get="?".http_build_query($_GET);
}


?>
<div id="server-response-text_<?=$interface?>"></div>
<div id="form_interface_<?=$interface?>">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url("adm/io-zform",["interface"=>$interface,"action"=>"edit"]).$get);
$form->setAttribute("id","zform_".$interface);
$form->prepare();
$formLabel = $this->plugin('formLabel');
$flagError=false;
echo $this->form()->openTag($form);
foreach ($form as $k=>$item){
    $i=$form->get($k);
    $type=$item->getAttribute("type");

    $error=$i->getMessages();
    if (!empty($error)){$flagError=true;}
    if ($type=="submit") {
        //для кнопки не выводим группу
        echo $this->formSubmit($form->get($k));
    } elseif ($type=="hidden"){
        echo $this->FormHidden($i);
    } else {

        ?>
        <div class="form-group">

        <?php //echo $type.' ';
        switch ($type){
            case "select":{
                echo $this->formLabel($i).$this->FormSelect($i);
                break;
            }
            case "multi_checkbox":{
                $m=$this->FormMultiCheckbox();
                $m->setSeparator("<br/>");
                echo $this->formLabel($i).'<div class="form-check pt-2">'.$m->Render($i).'</div>';
                break;
            }
            case "radio":{
                $m=$this->FormRadio();
                $m->setSeparator("<br/>");
                echo $this->formLabel($i).'<div class="form-check pt-2">'.$m->Render($i).'</div>';
                break;
            }
            case "checkbox":{
                echo $this->FormCheckbox($i).$this->formLabel($i);
                break;
            }
            case "button":{
                echo $this->FormButton($i);
                break;
            }

            default:{
                echo $this->formLabel($i).$this->formElement($i);
            }
        }
        ?>
        <?=(!empty($error)) ? '<div class="alert alert-danger" role="alert">'.implode("<br>",$error).'</div>':"" ?>
          </div>
        <?php
    }

}
?>
<?= $this->form()->closeTag() ?>

</div>
<script type="text/javascript">
$(document).ready(function() {
$(".ckeditor").ckeditor();
<?=(!empty($actionEvent["FormAfterSubmitOkEvent"]) && !$flagError && $_SERVER['REQUEST_METHOD']=="POST") ? $actionEvent["FormAfterSubmitOkEvent"]:"" ?>
    $(".dtpicker").datetimepicker({timeInput: true,timeFormat: "HH:mm:ss",dateFormat:"dd.mm.yy"});
  $('#zform_<?=$interface?>' ).on( 'submit', function (e) {
      $("body").append(zform_overlay);
      e.preventDefault();
      $( this ).ajaxSubmit({
          target:"#form_interface_<?=$interface?>",
          error: function (e) {
              $(".zformoverlay").remove();
              if (e.status==418){
                  //ошибка валидатора формы, выводим ее с сообщениями
                  $("#server-response-text_<?=$interface?>").text("Ошибка").addClass("alert alert-danger").removeClass("alert-success");
                  $("#form_interface_<?=$interface?>").html(e.responseText);
              } else {
                  //прояайя ошибка серии 4ХХ, выводим ответ сервера
                  $("#server-response-text_<?=$interface?>").html(e.responseText).addClass("alert alert-danger").removeClass("alert-success");
              }
          },
          success: function (e) {
              //успех
              $(".zformoverlay").remove();
              $("#server-response-text_<?=$interface?>").text("Информация успешно записана").addClass("alert alert-success").removeClass("alert-danger");
          }
  });
    return false;
});

});
</script>
