<?php
/*
* генерирует zform
* на входе:
* $options - опции из соответсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса
* $form - сама форма в виде данных формата Zend
*/

$options=$this->options;
$get="";
if (isset($_GET)){
    $get="?".http_build_query($_GET);
}


?>
<div id="server-response-text"></div>
<div id="form_interface_<?=$interface?>">
<?php
$form = $this->form;
$form->setAttribute('action', $this->url("adm/io-zform",["interface"=>$interface,"action"=>"edit"]).$get);
$form->setAttribute("id","zform_".$interface);
$form->prepare();
$formLabel = $this->plugin('formLabel');

echo $this->form()->openTag($form);
foreach ($form as $k=>$item){
    $i=$form->get($k);
    $type=$item->getAttribute("type");
    if ($type=="submit") {
        //для кнопки не выводим группу
        echo $this->formSubmit($form->get($k));
    } elseif ($type=="hidden"){
        echo $this->FormHidden($i);
    } else {

        ?>
        <div class="form-group">
    <?=$this->formLabel($i)?>
        <?php //echo $type.' ';
        switch ($type){
            case "select":{
                echo $this->FormSelect($i);
                break;
            }
            case "multi_checkbox":{
                $m=$this->FormMultiCheckbox();
                $m->setSeparator("<br/>");
                echo '<div class="form-check pt-2">'.$m->Render($i).'</div>';
                break;
            }
            default:{
                echo $this->formElement($i);
            }
        }
        ?>
        <?=$this->formElementErrors($i)?>
          </div>
        <?php
    }

}
?>
<?= $this->form()->closeTag() ?>
</div>
<script type="text/javascript">
$(document).ready(function() {
    $(".dtpicker").datetimepicker({timeInput: true,timeFormat: "HH:mm:ss",dateFormat:"dd.mm.yy"});
  $('#zform_<?=$interface?>' ).on( 'submit', function (e) {
  e.preventDefault();
  $( this ).ajaxSubmit({
      target:"#form_interface_<?=$interface?>",
      error: function (e) {$("#server-response-text").html(e.responseText)},
      success: function (e) {$("#usersall").trigger("reloadGrid");}
  });
    return false;
});

});
</script>
