<?php
/*
* генерирует zform
* на входе:
* $options - опции из соответсвующей секции конфига
* $interface -  это имя глобальное имя интерфейса
* 
*/

$options=$this->options;

\Zend\Debug\Debug::dump($options);
$get="";
if (isset($_GET)){
    $get="?".http_build_query($_GET);
}

?>
<div id="<?=$options["container"]?>" class="zform-default" <?=$options["container-attr"]?>>
<div><?=$options["caption"]?></div>
<div id="form_<?=$options["container"]?>"></div>
<div><?=$options["podval"]?></div>
</div>
<script type="text/javascript">
$(document).ready(function() {
$("#form_<?=$options["container"]?>").load("<?=$this->url("adm/io-zform",["interface"=>$this->interface,"action"=>"read"]).$get?>",
    function(response, status, xhr){
    if (status!="success"){
        $("#form_<?=$options["container"]?>").html(response)
    }
});
});
</script>
