<!doctype html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<title>Система управления сайтом</title>
<link href="/css/admin/jquery-ui-timepicker-addon.css" rel="stylesheet" type="text/css">
<link href="/css/admin/jquery-ui.min.css" rel="stylesheet" type="text/css">
<link href="/css/admin/jquery-ui.theme.min.css" rel="stylesheet" type="text/css"> 
<link href="/css/admin/jquery-ui-1.12.icon-font.min.css" rel="stylesheet" type="text/css">     
<link href="/css/admin/bootstrap.css" rel="stylesheet" type="text/css">   
<link href="/css/admin/ui.jqgrid.css" rel="stylesheet" type="text/css">   
<link href="/css/admin/admin.css" rel="stylesheet" type="text/css">
<script src="/js/admin/jquery-3.1.0.min.js" type="text/javascript"></script> 
<script src="/js/admin/jquery.cookie.js" type="text/javascript"></script>   
<script src="/js/admin/jquery-ui.min.js" type="text/javascript"></script>
<script src="/js/admin/jquery.jqGrid.min.js" type="text/javascript"></script>   
<script src="/js/admin/grid.locale-ru.js" type="text/javascript"></script> 
<script src="/js/admin/jqgrid-ext.js?<?=date("d.Y")?>" type="text/javascript"></script>    
<script src="/js/admin/jquery-ui-timepicker-addon.min.js" type="text/javascript"></script>
<script src="/js/admin/jquery.form.min.js" type="text/javascript"></script>
<script src="/js/admin/zform.js?<?=date("d.Y")?>" type="text/javascript"></script>
<script type="text/javascript" src="/htmledit/ckeditor.js"></script>
<script type="text/javascript" src="/htmledit/adapters/jquery.js"></script>
<script src="/js/admin/admin_lib.js?<?=date("d.Y")?>" type="text/javascript"></script>
<?= $this->headScript()?>
</head><body>
<?php
//костыли для обработки отдельного интерфейса с данными, без меню
if (empty($_GET['get_interface_input']))
{
?>
<table class="main">
  <tbody>
    <tr>
      <td class="lmenu"><a target="_blank" href="https://www.masterflash.ru"><img src="/img/simba.jpg" alt="" /></a><br>
<?=$this->adminMenu()->render();?></td>
      <td style="vertical-align:top" id="contant-container"><?= $this->content ?></td>
    </tr>
  </tbody>
</table>
<?php
}
else {echo $this->content ;}
?>
<?= $this->inlineScript() ?>
</body>
</html>