<!doctype html>
<html lang="ru">
<head>
<meta charset="UTF-8">
<title>Система управления сайтом</title>
<?php
    $asset=$this->asset('backend');
    foreach ($asset['css'] as $css){
        $this->headLink()->appendStylesheet($this->basePath($css));
    }
    foreach ($asset['js'] as $js){
        $this->headScript()->appendFile($this->basePath($js));
    }
echo $this->headLink();
echo $this->headScript();
?>
</head><body>
<?php
//костыли для обработки отдельного интерфейса с данными, без меню
if (empty($_GET['get_interface_input']))
{
?>
<table class="main">
  <tbody>
    <tr>
      <td class="lmenu"><a target="_blank" href="https://www.masterflash.ru"><img src="/img/simba.jpg" alt="" /></a><br>
          <div id="admin_menu_container"></div>
        </td>
      <td style="vertical-align:top" id="contant-container"><?= $this->content ?></td>
    </tr>
  </tbody>
</table>
<?php
}
else {echo $this->content ;}
?>
<?= $this->inlineScript() ?>
</body>
</html>