<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<style>
TR, TD, BODY,input{color:#000000; font-family: Verdana, sans-serif; font-size: 11px;}
FORM{margin:0px;}
table{
}
div {
        position        : absolute;
        top             : 44%;
        height          : 110px;
        margin-top      : -120px;
        margin: 0 auto;
        left:42%;
		        border-width: 6px;
        border-color: #F3F3F3;
        border-style:solid;
		height:96px

}
</style>
</head><body>
<?= $this->content ?>
</body>
</html>