<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        html {
            height: 100%
        }
        
        TR,
        TD,
        BODY,
        input {
            color: #000000;
            font-family: Verdana, sans-serif;
            font-size: 16px;
        }
        
        body {
            display: -ms-flexbox;
            display: flex;
            -ms-flex-align: center;
            align-items: center;
            padding: 0;
            margin: 0;
            text-align: center;
            height: 100%
        }
        
        FORM {
            margin: 0px;
        }
        
        p.error {
            margin: 0;
            color: red
        }
        
        td {
            vertical-align: top
        }
        
        .form-signin {
            width: 100%;
            max-width: 516px;
            padding: 15px;
            margin: auto;
        }
        
        table {
            border-width: 4px;
            border-color: #F3F3F3;
            border-style: solid;
            padding: 10px
        }
    </style>
</head>

<body>
    <?= $this->content ?>
</body>
</html>